name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t siddtheone/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_UNAME
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_UNAME: ${{ secrets.DOCKER_UNAME }}
      - run: docker push siddtheone/auth
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_AT }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment auth-depl
